package com.yuanyue.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-04-20T17:55:18.141+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://webservice.yuanyue.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "getAllUserInfo", targetNamespace = "http://webservice.yuanyue.com/", className = "com.yuanyue.webservice.GetAllUserInfo")
    @ResponseWrapper(localName = "getAllUserInfoResponse", targetNamespace = "http://webservice.yuanyue.com/", className = "com.yuanyue.webservice.GetAllUserInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.yuanyue.webservice.UserInfoArray getAllUserInfo();

    @WebMethod
    @RequestWrapper(localName = "getRoleByUser", targetNamespace = "http://webservice.yuanyue.com/", className = "com.yuanyue.webservice.GetRoleByUser")
    @ResponseWrapper(localName = "getRoleByUserResponse", targetNamespace = "http://webservice.yuanyue.com/", className = "com.yuanyue.webservice.GetRoleByUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.yuanyue.webservice.Role> getRoleByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.yuanyue.webservice.User arg0
    );

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.yuanyue.com/", className = "com.yuanyue.webservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.yuanyue.com/", className = "com.yuanyue.webservice.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
